// blog.js - Complete with all your articles

const posts = [
  {
    slug: "jwt-authentication",
    title: "JWT Authentication in ASP.NET Core: Lessons from a Production Multi-Tenant SaaS",
    category: ".NET",
    date: "July 2026",
    read: "10 min read",
    icon: "fa-shield-halved",
    color: "linear-gradient(135deg,#5d2bbd,#a270ff)",
    excerpt: "How we designed secure, scalable JWT authentication for enterprise SaaS applications while keeping security, performance, and developer productivity in balance.",
    sections: [
      ["Why JWT Became Our Authentication Strategy", "Authentication is often one of the first features developers implement, but it's also one of the easiest to get wrong. While working on production applications like NeoPoulx and Virudhi, our APIs had to support multiple users, different permission levels, and isolated tenant data. Traditional server-side session management quickly became difficult to scale because every authenticated user required session state to be maintained on the server. Instead, we adopted JSON Web Tokens (JWT) with ASP.NET Core. JWT gave us a stateless authentication mechanism where every request carried its own authentication information, allowing the backend to remain lightweight while supporting multiple concurrent users across different organizations. The biggest advantage wasn't simply avoiding sessions—it was designing an authentication model that naturally fit a multi-tenant SaaS architecture."],
      ["Designing Authentication for Multi-Tenant Applications", "Authentication in a multi-tenant system goes beyond verifying usernames and passwords. Every authenticated request must answer three important questions: Who is the user? Which tenant does the user belong to? What actions is the user allowed to perform? Instead of querying the database repeatedly, we embedded only the essential information inside JWT claims. A typical token generated by our API contained: User ID, Tenant ID, Email, Assigned Role, Token Expiration. This allowed downstream services to authorize requests immediately without additional authentication lookups. Keeping the token compact also reduced network overhead while avoiding unnecessary exposure of sensitive information."],
      ["The Authentication Flow We Used", "Our authentication pipeline remained intentionally simple. 1. Users authenticated through the React application over HTTPS. 2. ASP.NET Core validated credentials against SQL Server. 3. After successful authentication, the API generated a signed JWT containing only essential claims. 4. The React client stored the token securely and attached it to every protected API request using the Authorization Bearer header. 5. ASP.NET Core middleware validated: Signature, Issuer, Audience, Expiration, Signing key. 6. Only after successful validation were secured controllers executed. Because authentication happened inside middleware, every protected endpoint shared exactly the same security guarantees without duplicating validation logic."],
      ["ASP.NET Core Configuration That Worked Well", `builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ClockSkew = TimeSpan.FromSeconds(30)
        };
    });`],
      ["Claims and Role-Based Authorization", "Authentication verifies identity. Authorization determines permissions. These two concerns should always remain separate. For example, within the Virudhi Admin Portal, administrative operations such as managing medicinal plants, user records, and dashboard statistics required elevated privileges. Instead of relying on frontend logic, authorization was enforced entirely on the server using ASP.NET Core policies. Even if someone attempted to bypass the UI and directly invoke API endpoints, requests without the required role were rejected before business logic executed. This server-side enforcement significantly reduced the attack surface while keeping authorization rules easy to understand."],
      ["Production Lessons We Learned", "Working in production taught us that authentication isn't something you configure once and forget. Some practices consistently proved valuable: Always enforce HTTPS across every environment. Never commit signing keys to source control. Keep JWTs short-lived. Store only essential claims inside tokens. Validate issuer, audience, and signing key on every request. Avoid placing confidential business information inside JWT payloads. Centralize authentication logic instead of implementing custom validation in controllers. During Rapid Response Team (RRT) production support, standardized authentication made debugging significantly easier because authentication failures were immediately distinguishable from application errors."],
      ["Testing Authentication Beyond the Happy Path", "Authentication testing shouldn't stop after verifying successful login. Our test scenarios included: Valid authenticated requests, Expired tokens, Invalid signatures, Incorrect issuer, Wrong audience, Missing Authorization headers, Users without required roles, Tenant access validation, Malformed JWT payloads. Testing these scenarios early prevented many production issues that otherwise would have surfaced only after deployment."],
      ["Monitoring Authentication in Production", "Logging authentication failures proved almost as valuable as authentication itself. We included: Correlation IDs, User identifiers (where appropriate), Request timestamps, Response status codes, Authentication failure reasons. These logs greatly improved collaboration between development and support teams, especially when investigating customer issues through Redmine."],
      ["Key Takeaways", "JWT authentication works exceptionally well for modern ASP.NET Core applications—but only when implemented thoughtfully. The token itself is only one piece of the solution. A secure production implementation also requires: Proper claims design, Strong server-side authorization, Secure key management, Short-lived tokens, Thorough validation, Comprehensive testing, Meaningful monitoring. Looking back at both NeoPoulx and Virudhi, JWT wasn't simply a replacement for sessions. It became the foundation for building scalable, secure, and maintainable APIs."]
    ]
  },
  {
    slug: "production-rest-apis",
    title: "Building Production-Ready REST APIs in ASP.NET Core",
    category: ".NET",
    date: "July 2026",
    read: "11 min read",
    icon: "fa-diagram-project",
    color: "linear-gradient(135deg,#4d257e,#d15da7)",
    excerpt: "The engineering practices that helped us build reliable, maintainable APIs capable of supporting production workloads, enterprise clients, and rapid incident resolution.",
    sections: [
      ["Why Production APIs Need More Than CRUD", "Building a REST API is relatively straightforward. Building one that remains reliable under continuous client usage, integrates with multiple frontend applications, and is easy to troubleshoot during production incidents is an entirely different challenge. While working on production applications such as NeoPoulx and Virudhi, I realized that the biggest improvements rarely came from adding new features—they came from improving consistency, reliability, and maintainability. Enterprise APIs aren't judged only by how quickly they return data. They're evaluated by how predictable they are when something goes wrong."],
      ["Designing APIs Around Business Domains", "One lesson that significantly improved our backend architecture was organizing APIs around business capabilities instead of database tables. Instead of creating controllers that simply mirrored SQL tables, endpoints were grouped around real business workflows. For example, rather than exposing generic CRUD operations, endpoints represented actions such as: User Authentication, Plant Discovery, Disease Identification, Dashboard Analytics, Administration, User Management. This approach made the API easier to understand, reduced unnecessary endpoint growth, and aligned backend development with actual product requirements."],
      ["Keeping Controllers Lightweight", "A common mistake in many applications is allowing controllers to become responsible for everything—validation, business rules, database access, logging, and response formatting. We avoided this by following a simple responsibility model. Controllers handled: Request validation, Model binding, Returning HTTP responses. Business logic remained inside service classes, while repositories handled database interactions. This separation made the codebase easier to maintain, simplified testing, and reduced the chances of introducing regressions during feature updates."],
      ["Designing Consistent API Responses", "One practice that greatly improved frontend integration was maintaining consistent response structures. Whether a request succeeded or failed, clients always received predictable responses."],
      ["Meaningful HTTP Status Codes", "Choosing the correct HTTP status code seems like a small detail, but it improves API usability considerably. Some conventions we consistently followed included: 200 OK – Successful data retrieval, 201 Created – Resource successfully created, 204 No Content – Successful deletion, 400 Bad Request – Validation failures, 401 Unauthorized – Missing or invalid authentication, 403 Forbidden – Authenticated but insufficient permissions, 404 Not Found – Requested resource unavailable, 500 Internal Server Error – Unexpected server failures."],
      ["Validation Before Business Logic", "Accepting invalid requests into business logic often creates unnecessary complexity. ASP.NET Core's built-in model validation allowed us to reject malformed requests early."],
      ["Exception Handling That Users Never Notice", "No production application is completely free from unexpected errors. The goal isn't eliminating every exception—it's handling them gracefully. Instead of returning raw exception messages, we used centralized exception handling middleware to log technical details internally, return user-friendly error responses, and prevent sensitive implementation details from leaking."],
      ["Performance Matters More Than You Think", "Performance optimization doesn't always require complex architecture. Some practical improvements consistently delivered noticeable benefits: Using asynchronous database operations, Returning only required fields, Applying pagination for large datasets, Optimizing SQL queries."],
      ["Logging That Actually Helps During Incidents", "One responsibility of serving as an RRT Lead was investigating production issues under time pressure. Good logging often determined how quickly an issue could be resolved."],
      ["Security as a Default Practice", "Every production API should assume that incoming requests cannot be trusted. Our standard security practices included: JWT authentication, Role-based authorization, HTTPS enforcement, Input validation, Parameterized database queries."],
      ["Lessons From Supporting Production Systems", "Production support teaches lessons that tutorials rarely cover. Some of the practices that consistently paid off were: Keep APIs simple and predictable, Standardize response formats, Fail gracefully with meaningful errors, Log enough information for troubleshooting."],
      ["Final Thoughts", "A production-ready API isn't defined by the framework it uses—it's defined by how reliably it behaves in real-world conditions. ASP.NET Core provides an excellent foundation, but long-term success comes from thoughtful architecture, consistent design, strong validation, effective logging, and disciplined engineering practices."]
    ]
  },
  {
    slug: "rrt-leadership",
    title: "What Leading a Rapid Response Team Taught Me",
    category: "Leadership",
    date: "July 2026",
    read: "9 min read",
    icon: "fa-people-group",
    color: "linear-gradient(135deg,#7a2347,#ee3c7b)",
    excerpt: "Lessons from coordinating an 8-member engineering team through high-priority production incidents, balancing technical problem-solving with communication, ownership, and continuous improvement.",
    sections: [
      ["When Production Goes Down, Priorities Change", "Every software engineer enjoys building new features. Production support teaches a very different skill. When a critical issue affects customers, deadlines, sprint planning, and feature development immediately become secondary. The only priority is restoring service safely and quickly. As the Rapid Response Team (RRT) Lead, I coordinated an eight-member team responsible for investigating production issues, identifying root causes, assigning ownership, and ensuring that fixes reached customers with minimal disruption. Those experiences fundamentally changed how I approach software engineering."],
      ["Leadership Starts Before the Investigation", "One of the biggest lessons I learned was that production incidents become chaotic only when responsibilities are unclear. Whenever a high-priority ticket arrived, the first objective wasn't solving the bug immediately. It was creating structure. Our initial response usually focused on: Understanding the business impact, Identifying affected customers, Assigning investigation owners, Establishing communication channels, Defining immediate next steps. Creating clarity early prevented duplicate work and allowed every engineer to focus on solving a specific part of the problem."],
      ["Root Cause Matters More Than Quick Fixes", "The fastest solution isn't always the best solution. During production support, it's tempting to apply a quick patch simply to close the ticket. However, recurring issues consume far more engineering time than a carefully designed permanent solution. Every incident became an opportunity to ask questions such as: Why did this happen? Why wasn't it detected earlier? Could monitoring have identified it sooner? Is the architecture contributing to the issue? How do we prevent this from happening again? This mindset shifted our team from reactive support toward continuous improvement."],
      ["Communication Is Just as Important as Technical Skills", "One misconception about incident response is that technical ability alone determines success. In reality, communication often becomes the deciding factor. As RRT Lead, I regularly coordinated between developers, QA engineers, project managers, client-facing teams, and enterprise customers. Providing regular progress updates helped stakeholders understand what was happening without overwhelming them with technical details."],
      ["Staying Calm Under Pressure", "Production incidents rarely happen at convenient times. Working under pressure taught me to avoid making assumptions. Instead, I learned to rely on evidence. Our investigations typically followed a structured process: 1. Reproduce the issue. 2. Review logs and recent deployments. 3. Verify database behavior. 4. Identify the exact failure point. 5. Validate the fix in a controlled environment. 6. Monitor production after deployment."],
      ["Documentation Saves Future Teams", "One improvement that consistently paid off was documenting every significant incident. After resolving an issue, we captured: Root cause, Business impact, Resolution steps, Preventive actions, Deployment notes, Monitoring improvements. These knowledge articles became valuable references for future investigations."],
      ["Measuring Success Beyond Ticket Closure", "Closing a production ticket isn't the end of the work. A successful incident response should also answer: Was the root cause eliminated? Were preventive improvements implemented? Were monitoring gaps addressed? Was documentation updated?"],
      ["The Human Side of Leadership", "Leading an engineering team isn't only about assigning work. It's about creating an environment where people can contribute effectively. Encouraging collaboration instead of competition helped investigations progress more smoothly."],
      ["Lessons I'll Carry Into Every Engineering Role", "Serving as an RRT Lead reshaped how I think about software development. Some principles continue to influence every project I work on: Build systems that are easy to troubleshoot. Prioritize long-term fixes over temporary workarounds. Communicate clearly during uncertainty. Document solutions so knowledge is shared."],
      ["Final Thoughts", "Leadership in engineering isn't defined by job titles. It's demonstrated during challenging moments when systems fail, customers are affected, and teams must work together under pressure. Leading the Rapid Response Team taught me that successful incident management depends on more than technical expertise. It requires structured thinking, effective communication, empathy, and a commitment to continuous improvement."]
    ]
  },
  {
    slug: "campus-recruitment",
    title: "Representing My Company During Campus Recruitment",
    category: "Community",
    date: "July 2026",
    read: "8 min read",
    icon: "fa-users",
    color: "linear-gradient(135deg,#7a5314,#e1a13b)",
    excerpt: "How participating in multi-college hiring drives across Odisha changed my perspective on recruitment, employer branding, and building meaningful connections with future engineers.",
    sections: [
      ["More Than Just Hiring", "When people think about campus recruitment, they often picture aptitude tests, technical interviews, and offer letters. What I experienced was much broader. I had the opportunity to represent my company during campus hiring drives across multiple engineering colleges in Odisha, interacting with hundreds of aspiring graduates, coordinating with placement teams, and helping identify candidates for technical roles. The experience taught me that successful campus recruitment isn't simply about filling vacancies—it's about creating a positive first impression of the company and building long-term relationships with future talent."],
      ["Being the First Face of the Company", "For many students, campus recruitment was their very first interaction with our organization. That meant every conversation mattered. Whether introducing the company during a pre-placement session or answering individual questions after presentations, I realized that students weren't only evaluating the role—they were evaluating the people representing the organization."],
      ["Visiting Multiple Colleges, Meeting Diverse Talent", "Each campus brought a unique environment. Meeting candidates from different colleges reinforced an important lesson: Academic scores alone rarely tell the complete story. Some of the most promising candidates were those who displayed curiosity, adaptability, teamwork, and a genuine willingness to learn."],
      ["Organizing a Smooth Hiring Experience", "A successful hiring drive depends on careful planning behind the scenes. Every visit involved coordinating with college placement officers, student coordinators, technical interview panels, HR representatives, and company leadership. Small operational details often made the biggest difference."],
      ["Employer Branding Happens in Every Interaction", "One of my biggest takeaways was that employer branding doesn't begin with marketing campaigns. It begins with people. Students remember how they are treated throughout the recruitment process. Every interaction contributes to how an organization is perceived on campus."],
      ["Communication Makes the Difference", "Coming from a technical background, I initially expected campus recruitment to focus primarily on assessing programming skills. Instead, I found myself relying heavily on communication. This experience strengthened skills that continue to benefit me in engineering roles today: Public speaking, Stakeholder communication, Active listening, Presentation delivery."],
      ["Lessons That Continue to Shape My Career", "Representing my company during campus recruitment changed how I think about hiring. Today, whenever I evaluate engineering teams or workplace culture, I remember the qualities that consistently stood out in successful candidates: Curiosity over memorization, Problem-solving over perfection, Communication alongside technical ability."],
      ["Looking Beyond Recruitment", "Campus hiring wasn't just about identifying talent. It was also an opportunity to inspire students who were beginning their professional journeys. Being able to share practical experiences and answer questions honestly made the role personally rewarding."],
      ["Final Thoughts", "Representing my company during campus recruitment gave me a perspective that extends beyond software development. It taught me that organizations build their reputation one conversation at a time. Whether solving production issues, developing enterprise applications, or interacting with students at a campus drive, professionalism, communication, and authenticity consistently create the strongest impact."]
    ]
  },
  {
    slug: "communication-engineers",
    title: "Why Communication Is a Superpower for Software Engineers",
    category: "Public Speaking",
    date: "July 2026",
    read: "8 min read",
    icon: "fa-microphone-lines",
    color: "linear-gradient(135deg,#2c506f,#528cb6)",
    excerpt: "The technical skill that rarely appears in job descriptions but consistently determines project success, leadership opportunities, and career growth.",
    sections: [
      ["We Spend More Time Talking Than Coding", "When I began my career, I believed software engineering was primarily about writing clean code and solving technical problems. That assumption changed quickly after working on production systems. On any given day, I found myself discussing requirements with stakeholders, explaining production issues to clients, coordinating with teammates, reviewing pull requests, documenting solutions, and presenting updates during meetings. Writing code remained important, but communication became the thread connecting every part of the development process."],
      ["Great Software Is Built Through Collaboration", "Modern software development is rarely an individual effort. A single feature may involve frontend developers, backend engineers, QA analysts, DevOps teams, designers, product managers, and business stakeholders. Clear communication helps teams: Understand requirements correctly, Identify risks early, Resolve blockers quickly, Share knowledge effectively, Avoid misunderstandings that lead to costly rework."],
      ["Explaining Technical Ideas Simply", "One lesson I learned while working with both technical and non-technical stakeholders is that expertise isn't demonstrated by using complex terminology. It's demonstrated by making complex concepts easy to understand. The goal isn't to impress people with technical vocabulary. The goal is to help everyone understand the problem well enough to make informed decisions."],
      ["Communication During Production Incidents", "Some of the most valuable communication lessons came while serving as the Rapid Response Team (RRT) Lead. During production incidents, technical expertise is essential—but so is keeping everyone informed. Different audiences need different information."],
      ["Listening Is Just as Important as Speaking", "Communication isn't only about presenting ideas. It's also about listening carefully. Active listening helped me: Clarify ambiguous requirements, Understand client expectations, Identify the actual root cause of issues, Build stronger relationships with teammates."],
      ["Documentation Is Communication Too", "One of the most overlooked forms of communication is documentation. Well-written documentation benefits everyone: New developers onboard faster, Production issues are easier to investigate, APIs become easier to integrate, Knowledge remains available even when team members change."],
      ["Presenting Ideas with Confidence", "Throughout my career, I've had opportunities to conduct presentations, participate in seminars, represent my organization during campus recruitment, and communicate with clients. Being comfortable presenting ideas has helped me: Share technical solutions with stakeholders, Lead engineering discussions, Explain complex implementations, Mentor teammates."],
      ["Communication Accelerates Career Growth", "As engineers gain experience, their responsibilities naturally expand beyond coding. Senior engineers and technical leaders spend increasing amounts of time: Mentoring teammates, Reviewing designs, Leading discussions, Coordinating across teams. The ability to explain, persuade, collaborate, and build consensus often distinguishes engineers who grow into leadership roles."],
      ["Practical Habits That Made Me a Better Communicator", "Communication is a skill that improves with consistent practice. Some habits that have helped me include: Asking clarifying questions before starting implementation, Keeping technical explanations concise and structured, Tailoring communication to the audience, Writing clear documentation, Sharing progress regularly during projects."],
      ["Final Thoughts", "Software engineering is fundamentally about solving problems for people. Code is one part of that process. Communication connects everything else. Looking back at my experiences—from building enterprise applications and supporting production systems to leading incident response and participating in campus recruitment—one skill has consistently amplified every technical contribution I made: the ability to communicate clearly, collaborate effectively, and build strong professional relationships."]
    ]
  },
  {
    slug: "dotnet-job-market-india",
    title: "How to Get a .NET Developer Job in India in 2026",
    category: "Career",
    date: "July 2026",
    read: "8 min read",
    icon: "fa-chart-line",
    color: "linear-gradient(135deg,#96410d,#dc892a)",
    excerpt: "What recruiters are looking for today and how aspiring developers can build the skills, portfolio, and confidence to stand out in a competitive hiring market.",
    sections: [
      ["The .NET Job Market Has Changed", "The demand for .NET developers in India continues to grow as organizations modernize enterprise applications and build cloud-native solutions. However, the hiring process has changed significantly over the last few years. Recruiters are no longer looking for candidates who simply list C# or ASP.NET on their resumes. They want developers who can demonstrate practical problem-solving skills, understand modern development workflows, and contribute to production-ready applications from day one."],
      ["Build Strong Fundamentals Before Learning Frameworks", "Many aspiring developers make the mistake of jumping directly into ASP.NET Core without having a solid understanding of C#. Before focusing on advanced topics, make sure you're comfortable with: Object-Oriented Programming (OOP), Collections and Generics, Exception Handling, LINQ, Async and Await, File Handling, Delegates and Events, Basic Design Patterns."],
      ["Learn the Technologies Companies Actually Use", "A modern .NET developer is expected to work with much more than ASP.NET Core. Some of the most in-demand skills include: ASP.NET Core Web API, Entity Framework Core, SQL Server, REST APIs, JWT Authentication, Git and GitHub, Docker fundamentals, Azure basics, React or Angular, Unit Testing."],
      ["Build Projects That Demonstrate Real Skills", "Instead of creating simple CRUD applications, focus on projects that solve practical problems and include features commonly found in production systems. Good portfolio projects might include: Employee Management System, Inventory Management Platform, Hospital Management System, Multi-Tenant SaaS Dashboard."],
      ["A Strong GitHub Profile Makes a Difference", "Recruiters and hiring managers often review GitHub profiles before scheduling interviews. To make your profile stand out: Upload complete projects with clear README files, Use meaningful commit messages, Organize repositories properly, Include screenshots of your applications."],
      ["Tailor Your Resume for Every Application", "Your resume is often your first opportunity to make an impression. An effective .NET resume should clearly highlight: Technical skills, Relevant work experience, Projects, Achievements, GitHub and portfolio links."],
      ["Prepare Beyond Coding Questions", "Technical interviews today evaluate much more than programming knowledge. Common discussion areas include: OOP concepts, ASP.NET Core architecture, REST API design, SQL queries and optimization, Dependency Injection, JWT Authentication, Entity Framework Core."],
      ["Don't Ignore Soft Skills", "Technical expertise is essential, but communication and collaboration often influence hiring decisions just as much. Developers regularly interact with teammates, project managers, QA engineers, and clients."],
      ["Keep Learning After Every Interview", "Rejections are a normal part of the job search process. After each interview, ask yourself: Which questions were difficult? Which concepts need revision? Did I explain my projects confidently?"],
      ["Final Thoughts", "Getting a .NET developer job in India today requires more than technical knowledge. Focus on strengthening your fundamentals, building meaningful projects, maintaining an active portfolio, and developing strong communication skills."]
    ]
  },
  {
    slug: "community-management",
    title: "Community Management & Event Leadership: Building Strong Communities Beyond Technology",
    category: "Community",
    date: "July 2026",
    read: "7 min read",
    icon: "fa-users",
    color: "linear-gradient(135deg,#7a5314,#e1a13b)",
    excerpt: "How effective community management and well-planned events create meaningful connections, encourage collaboration, and develop leadership skills that extend far beyond the workplace.",
    sections: [
      ["Communities Are Built Through People, Not Events", "When people hear the term community management, they often think of organizing events or managing social media groups. In reality, community building is much more than that. A thriving community is created by bringing people together around a common purpose, encouraging participation, and ensuring that everyone feels welcomed and valued."],
      ["Every Successful Event Begins with Careful Planning", "An event that appears effortless on the day is usually the result of weeks of preparation behind the scenes. Successful event management involves much more than booking a venue or preparing an agenda. It requires defining clear objectives, assigning responsibilities, managing timelines, anticipating challenges, and coordinating with multiple stakeholders."],
      ["Leadership Is About Enabling Others", "One of the biggest lessons community management teaches is that leadership isn't about doing everything yourself. Large events are always the result of teamwork. An effective community leader empowers others by delegating responsibilities, encouraging collaboration, and recognizing every contribution."],
      ["Communication Keeps Everything Moving", "Even the best plans can fail without clear communication. Effective communication helps: Keep volunteers informed, Align organizing teams, Provide timely updates to participants, Resolve misunderstandings quickly."],
      ["Challenges Are Part of Every Event", "No event unfolds exactly as planned. The ability to remain calm and adapt quickly is one of the most valuable skills an event organizer can develop. Preparing backup plans, maintaining open communication, and making decisions with confidence help ensure that unexpected challenges have minimal impact."],
      ["Creating Experiences That People Remember", "The most successful events are not necessarily the largest ones. People remember how an event made them feel. Simple details—such as welcoming participants warmly, encouraging interaction, recognizing volunteers, and creating opportunities for networking—can leave a lasting impression."],
      ["Skills That Last Beyond the Event", "Community management develops a wide range of transferable skills that remain valuable throughout a professional career. Organizing events strengthens abilities such as: Leadership and teamwork, Public speaking and presentation, Time management, Problem-solving under pressure, Stakeholder coordination."],
      ["Building Communities Is a Continuous Journey", "Communities don't grow through one successful event. They grow through consistent engagement. Following up with participants, encouraging ongoing discussions, welcoming new members, and continuously improving based on feedback all contribute to a healthy and sustainable community."],
      ["Final Thoughts", "Community management and event leadership are about much more than organizing schedules or coordinating logistics. They are about bringing people together, creating opportunities for learning, encouraging collaboration, and building environments where individuals feel supported and motivated to grow."]
    ]
  },
  {
    slug: "public-speaking",
    title: "Public Speaking: The Skill That Shaped My Journey Beyond Technology",
    category: "Public Speaking",
    date: "July 2026",
    read: "8 min read",
    icon: "fa-microphone-lines",
    color: "linear-gradient(135deg,#2c506f,#528cb6)",
    excerpt: "From winning state and national-level competitions to representing Karnataka on national platforms and leading professional discussions, public speaking has been the foundation of my confidence, leadership, and career growth.",
    sections: [
      ["Every Opportunity Begins with the Confidence to Speak", "When people think about software engineering, they usually imagine programming languages, frameworks, and technical interviews. Very few people realize that one of the most valuable skills an engineer can develop is the ability to communicate with confidence. For me, public speaking has never been an extracurricular activity—it has been a defining part of my journey. Long before I started building enterprise applications or leading production teams, I was standing on stages, participating in debates, presenting research, and speaking before audiences at district, state, and national levels. Looking back, those experiences shaped far more than my communication skills. They taught me leadership, discipline, preparation, and the confidence to embrace opportunities that many people hesitate to take."],
      ["Winning on Stage Was Never Just About the Trophy", "One of the most memorable milestones in my journey was becoming a two-time First Prize winner at the State-Level Pratibha Karanji Elocution Competition, organized by the Government of Karnataka. Reaching the state finals itself required progressing through multiple rounds at the school, cluster, taluk, and district levels, competing with talented students from across Karnataka. Standing before large audiences and experienced judges demanded much more than memorizing a speech. Every competition required hours of preparation, understanding the topic in depth, structuring ideas logically, and delivering them with clarity and confidence. Winning twice taught me that effective communication isn't about speaking loudly—it's about speaking with purpose."],
      ["Representing Karnataka on a National Platform", "One experience that will always remain close to my heart was representing Karnataka in the Ek Bharat Shreshtha Bharat National Youth Exchange Program, an initiative by the Government of India designed to promote national integration, cultural exchange, and youth leadership. Being selected as one of the representatives from my state was both an honour and a responsibility. The program took me to Uttarakhand, where I had the opportunity to interact with participants from across India, exchange ideas, learn about different cultures, and participate in leadership and educational activities. During the program, I was honoured with the \"Visionary\" Award, recognizing my communication skills, leadership qualities, confidence, and overall personality."],
      ["Science Taught Me to Speak with Evidence", "Public speaking wasn't limited to debates and leadership events. It also became an important part of my academic journey. I had the privilege of representing Karnataka twice at the prestigious National Children's Science Congress (NCSC) through the National Level Science Seminar Competition. The first presentation focused on \"SRI (System of Rice Intensification): A Sustainable Method of Growing Rice,\" where I explored innovative agricultural techniques that improve water conservation and crop productivity. Later, at Baramati, Maharashtra, I presented \"Mushroom – A Magical Crop,\" highlighting its nutritional, environmental, medicinal, and economic significance. These experiences strengthened my analytical thinking and taught me how to present technical information in a way that diverse audiences could easily understand."],
      ["Public Speaking Prepared Me for Corporate Leadership", "When I entered the software industry, I expected coding to be the biggest part of my role. Instead, I quickly realized that communication influences almost every aspect of software development. Whether discussing requirements with stakeholders, explaining production issues to clients, coordinating with cross-functional teams, or presenting project updates, the confidence I had developed over years of public speaking became one of my greatest professional strengths."],
      ["Leadership Begins with Listening", "One lesson public speaking taught me is that communication isn't only about delivering speeches. It's equally about listening. Whether interacting with students during campus recruitment, collaborating with engineering teams, or speaking with enterprise clients, understanding the audience always comes before presenting ideas."],
      ["Beyond Awards, Beyond the Stage", "Throughout my journey, I have participated in numerous seminars, debates, presentations, leadership programs, and community initiatives, earning more than 250 certificates across academics, public speaking, cultural activities, technical events, and leadership programs. Each certificate represents a learning experience. Each stage represented an opportunity to improve."],
      ["Communication Is a Skill That Creates Opportunities", "Looking back, many of the opportunities I've received began with a conversation. Representing Karnataka on a national platform, receiving the Visionary Award, presenting scientific research at national conferences, leading engineering discussions, participating in campus recruitment drives, and coordinating teams all had one thing in common: They required effective communication."],
      ["Final Thoughts", "Public speaking has been one of the most influential skills in my personal and professional journey. From becoming a two-time State-Level Pratibha Karanji Elocution Champion, representing Karnataka in the Ek Bharat Shreshtha Bharat National Youth Exchange Program, receiving the Visionary Award in Uttarakhand, presenting research twice at the National Children's Science Congress, and later applying those same communication skills in the corporate world, every experience has contributed to the person I am today. As a software engineer, I believe technical expertise builds solutions. Communication builds opportunities. The combination of both has enabled me to contribute not only as a developer but also as a leader, collaborator, mentor, and representative of my organization."]
    ]
  }

];

// Card function - FIXED for hyphenated categories
function card(p) {
  const categorySlug = p.category.toLowerCase().replace(/\s+/g, '-');
  return `<article class="card" data-category="${categorySlug}">
    <div class="cover" style="background:${p.color}"><i class="fa-solid ${p.icon}"></i></div>
    <div class="card-body">
      <div class="meta">${p.date} &nbsp;·&nbsp; ${p.read}</div>
      <h2>${p.title}</h2>
      <p class="excerpt">${p.excerpt}</p>
      <span class="tag">${p.category}</span><br><br>
      <a class="read-link" href="articles/${p.slug}.html">Read full article <i class="fa-solid fa-arrow-right"></i></a>
    </div>
  </article>`;
}

// Updated initHome with proper matching
function initHome() {
  const grid = document.querySelector("#postGrid");
  if (!grid) return;

  const search = document.querySelector("#search");
  const empty = document.querySelector("#empty");
  let active = "all";

  function draw() {
    const q = search.value.toLowerCase().trim();
    const shown = posts.filter(p => {
      const postCategorySlug = p.category.toLowerCase().replace(/\s+/g, '-');
      return (active === "all" || postCategorySlug === active) &&
             (p.title.toLowerCase().includes(q) || p.excerpt.toLowerCase().includes(q));
    });
    grid.innerHTML = shown.map(card).join("");
    if (empty) empty.style.display = shown.length ? "none" : "block";
  }

  document.querySelector("#filters")?.addEventListener("click", (e) => {
    if (!e.target.matches("button")) return;
    document.querySelectorAll("#filters button").forEach(x => x.classList.remove("active"));
    e.target.classList.add("active");
    active = e.target.dataset.category;
    draw();
  });

  search?.addEventListener("input", draw);
  draw();
}

function initArticle() {
  const root = document.querySelector("[data-slug]");
  if (!root) return;

  const p = posts.find(x => x.slug === root.dataset.slug);
  if (!p) return;

  document.title = `${p.title} | Engineering Insights`;

  document.querySelector("#articleTitle").textContent = p.title;
  document.querySelector("#articleSubtitle").textContent = p.excerpt;
  document.querySelector("#articleMeta").textContent = `Published ${p.date} · ${p.read} · By Poornima Jain`;

  const body = document.querySelector("#articleBody");
  body.innerHTML = p.sections.map((s, i) => `
    <section id="section-${i+1}">
      <h2>${s[0]}</h2>
      <div>${s[1]}</div>
    </section>
  `).join("") + `<div class="callout"><strong>Note:</strong> This article reflects my practical experience.</div>`;

  const toc = document.querySelector("#tocList");
  if (toc) {
    toc.innerHTML = p.sections.map((s, i) => `<li><a href="#section-${i+1}">${s[0]}</a></li>`).join("");
  }
}

document.addEventListener("DOMContentLoaded", () => {
  initHome();
  initArticle();
});